default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: writing_competition_development

test:
  <<: *default
  database: writing_competition_test

production:
  <<: *default
  database: writing_competition_production
  username: writing_competition
  password: <%= ENV["DATABASE_PASSWORD"] %>
